---

# Config related to alarm system.  Config for various sensors
# will be included in their respective packages or in integrations
# for ESPhome

# see also: mqtt_sensors.yaml for RF and Wyze Sense sensors

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    name: Alarm
    code: !secret alarm_code

### @todo Door and Window opening events
### @body add automations for what needs to happen when a door or wondow opens
### when the alarm is armed and disarmed,  Also add automations to let us know
### when a door has been left open.

automation:

  - alias: Door opened
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        from: "off"
        to: "on"

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.whole_house
          volume_level: 0.8
      - service: tts.google_translate_say
        data_template:
          entity_id: media_player.whole_house
          message: the {{trigger.to_state.attributes.friendly_name}} opened

  - alias: Door left open
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
          - binary_sensor.fridge
          - binary_sensor.freezer
        to: "on"
        for:
          minutes: 5
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.whole_house
          volume_level: 0.8
      - service: tts.google_translate_say
        data_template:
          entity_id: media_player.whole_house
          message: the {{trigger.to_state.attributes.friendly_name}} was left open

  - alias: Door left open
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
          - binary_sensor.fridge
          - binary_sensor.freezer
        to: "on"
        for:
          minutes: 10
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.whole_house
          volume_level: 0.8
      - service: tts.google_translate_say
        data_template:
          entity_id: media_player.whole_house
          message: the {{trigger.to_state.attributes.friendly_name}} is still open after ten minutes
