---

# Batteries
sensor:

  - platform: mqtt
    name: "Fridge Battery Level"
    state_topic: "gosense/7778F8F3"
    device_class: battery
    value_template: "{{ value_json.properties.battery }}"

  - platform: template
    sensors:
      alarm_panel_battery:
        friendly_name: "Alarm Panel Battery"
        evice_class: battery
        value_template: "{{ state_attr('display.alarm_panel', 'battery_level') }}"
      alarm_clock_battery:
        friendly_name: "Alarm Clock Battery"
        evice_class: battery
        value_template: "{{ state_attr('display.alarm_clock', 'battery_level') }}"


automation:

  - alias: Watch Battery Low
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ticwatch_battery
        below: 30

    action:
      - service: persistent_notification.create
        data:
          title: TicWatch
          message: Battery level is starting to get Low
          notification_id: 0001

      - service: notify.mobile_app_pixel_xl_ariela
        data:
          title: TicWatch
          message: Battery Level is getting low
          icon: mdi:clock-alert-outline

  - alias: Watch Battery Critical
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ticwatch_battery
        below: 20

    action:
      - service: persistent_notification.create
        data:
          title: TicWatch
          message: Battery level is CRITICAL
          notification_id: 0001

      - service: notify.mobile_app_pixel_xl_ariela
        data:
          title: TicWatch
          message: Battery Level is CRITICAL
          icon: mdi:close-octagon
