---

automation:
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'on'
    from: 'off'
  action:
    - service: browser_mod.command
      data:
        command: popup
        large: true
        auto_close: true
        card:
          type: custom:more-info-card
          entity: camera.front_door
        deviceID:
          - 63a59e69-36e6756d
          - 3b3eda67-36d67dd5

    - delay: 0:60

    - service: browser_mod.command
      data:
        command: close-popup
