---

# display:
#   - platform: fully_kiosk
#     name: Alarm Panel
#     host: 192.168.1.53
#     password: !secret alarm_panel_fk_password
#
#   - platform: fully_kiosk
#     name: Alarm Clock
#     host: 192.168.1.45
#     password: !secret alarm_clock_fk_password
#
# variable:
#   alarm_clock:
#     value: 'Alarm Clock'
#     restore: true

### @todo integrate mdeia player and sensors from floorplan
### @bogy research whether the floorplan CCs will work without full
### floorplan integration
light:
  - platform: template
    lights:
      dashboard_screen:
        turn_on:
        turn_off:
        set_level:

binary_sensor:
  - platform: mqtt
    name: dashboard_motion
    state_topic: any/value
