---

automation:
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'on'
    from: 'off'
  action:
    service: browser_mod.command
    service_data:
      command: more-info
      entity_id: camera.front_door
      deviceID:
        - 63a59e69-36e6756d
        - 3b3eda67-36d67dd5
