---

# Config for vaious sensors that communicate with Home Assistant
# via the MQTT protocol.

binary_sensor:

  #### Contact Sensors ####

  - platform: mqtt
    name: "Fridge"
    state_topic: "gosense/7778F8F3"
    payload_on: 1
    payload_off: 0
    device_class: door
    value_template: "{{ value_json.metadata.properties.state }}"
    json_attributes_topic: "gosense/7778F8F3"
    # json_attributes_topic: "gosense/7778F8F3"

  - platform: mqtt
    name: "Test"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x317F0A"
    payload_off: "0x317F0E"
    device_class: opening
    value_template: "{{ value_json.RfReceived.Data }}"
    json_attributes_topic: "tele/rfbridge/STATE"

  - platform: mqtt
    name: "Front Door"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x301C0A"
    payload_off: "0x301C0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Back Door"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x346E0"
    payload_off: "0x346E0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Garage Door"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x319E0A"
    payload_off: "0x319E0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Garage Back Door"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x346A0A"
    payload_off: "0x346A0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Freezer"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0xB8CC0A"
    payload_off: "0xB8CC0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "not Fridge"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x7B080A"
    payload_off: "0x7B080E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Girls' Window 1"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x71520A"
    payload_off: "0x71520E"
    device_class: window
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Girls' Window 2"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x775A0A"
    payload_off: "0x775A0E"
    device_class: window
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Boy's Window 1"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0xE1870A"
    payload_off: "0xE1870E"
    device_class: window
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Boy's Window 2"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x31160A"
    payload_off: "0x31160E"
    device_class: window
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Mailbox"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x30FB0A"
    payload_off: "0x30FB0E"
    device_class: door
    value_template: "{{ value_json.RfReceived.Data }}"

    #### Motion Sensors ####

  - platform: mqtt
    name: "Living Room Motion"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x21EE9A"
    off_delay: 5
    device_class: motion
    value_template: "{{ value_json.RfReceived.Data }}"

  # - platform: mqtt
  #   name: "Wyze Motion"
  #   state_topic: "gosense/777A5038"
  #   payload_on: 1
  #   payload_off: 0
  #   device_class: motion
  #   value_template: "{{ value_json.metadata.properties.state }}"
  #   json_attributes_topic: "gosense/777A5038"
  #   json_attributes_template: "{{ value_json.properties | tojson }}"

  - platform: mqtt
    name: "Wyze Motion 2"
    unique_id: 779303F3
    payload_on: 1
    payload_off: 0
    device_class: motion
    state_topic: "gosense/779303F3"
    value_template: "{{ value_json.properties.state }}"
    json_attributes_topic: "gosense/779303F3"
    json_attributes_template: "{{ value_json.properties | tojson }}"

  - platform: mqtt
    name: "Wyze Motion 3"
    unique_id: 7793F55D
    payload_on: 1
    payload_off: 0
    device_class: motion
    state_topic: "gosense/7793F55D"
    value_template: "{{ value_json.properties.state }}"
    json_attributes_topic: "gosense/7793F55D"
    json_attributes_template: "{{ value_json.properties | tojson }}"

  - platform: mqtt
    name: "Wyze Motion 4"
    unique_id: 77931C95
    payload_on: 1
    payload_off: 0
    device_class: motion
    state_topic: "gosense/77931C95"
    value_template: "{{ value_json.properties.state }}"
    json_attributes_topic: "gosense/77931C95"
    json_attributes_template: "{{ value_json.properties | tojson }}"

  - platform: mqtt
    name: "Wyze Motion 5"
    unique_id: 7793FBD3
    payload_on: 1
    payload_off: 0
    device_class: motion
    state_topic: "gosense/7793FBD3"
    value_template: "{{ value_json.properties.state }}"
    json_attributes_topic: "gosense/7793FBD3"
    json_attributes_template: "{{ value_json.properties | tojson }}"

  - platform: mqtt
    name: "Alarm Panel Motion"
    state_topic: "/fully/event/onMotion/3b3eda67-36d67dd5"
    payload_on: "onMotion"
    off_delay: 10
    device_class: motion
    value_template: "{{value_json.event}}"
    json_attributes_topic: "/fully/deviceInfo/3b3eda67-36d67dd5"

  - platform: mqtt
    name: "Alarm Clock Motion"
    state_topic: "/fully/event/onMotion/63a59e69-36e6756d"
    payload_on: "onMotion"
    off_delay: 10
    device_class: motion
    value_template: "{{value_json.event}}"
    json_attributes_topic: "/fully/deviceInfo/63a59e69-36e6756d"

    ####  Mini Remotes ####

  - platform: mqtt
    name: "Remote Button 1"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x411533"
    payload_off: "0x41153C"
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Remote Button 2"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x4115C3"
    payload_off: "0x4115CC"
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Remote Button 3"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x411703"
    payload_off: "0x41170C"
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Remote Button 4"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x411D03"
    payload_off: "0x411D0C"
    value_template: "{{ value_json.RfReceived.Data }}"

  - platform: mqtt
    name: "Remote Button 5"
    state_topic: "tele/rfbridge/RESULT"
    payload_on: "0x413503"
    payload_off: "0x41350C"
    value_template: "{{ value_json.RfReceived.Data }}"

    #### Fully Kiosk Browser ####

  - platform: mqtt
    name: "Alarm Panel Plugged In"
    state_topic: "/fully/deviceInfo/3b3eda67-36d67dd5"
    payload_on: true
    payload_off: false
    device_class: plug
    value_template: "{{ value_json.isPlugged }}"

  - platform: mqtt
    name: "Alarm Clock Plugged In"
    state_topic: "/fully/deviceInfo/63a59e69-36e6756d"
    payload_on: true
    payload_off: false
    device_class: plug
    value_template: "{{ value_json.isPlugged }}"

sensor:
  - platform: mqtt
    name: "Alarm Panel Battery"
    state_topic: "/fully/deviceInfo/3b3eda67-36d67dd5"
    device_class: battery
    value_template: "{{ value_json.batteryLevel }}"

  - platform: mqtt
    name: "Alarm Clock Battery"
    state_topic: "/fully/deviceInfo/63a59e69-36e6756d"
    device_class: battery
    value_template: "{{ value_json.batteryLevel }}"

switch:
  - platform: mqtt
    name: "SP20-3"
    state_topic: "stat/sp20_3/POWER"
    command_topic: "cmnd/sp20_3/POWER"
    availability_topic: "tele/sp20_3/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    json_attributes_topic: "tele/sp20_3/SENSOR"
    json_attributes_template: "{{ value_json.ENERGY | tojson}}"
    optimistic: true
    qos: 0
    retain: true
