---

# School stuff

# Much of this is based on sensors created by skavala and brazenly repurposed from ccostan's repo  :-)

sensor:
  - platform: rest
    resource: https://raw.githubusercontent.com/atomicpapa/hassconfig/master/json_data/school_holidays.json
    name: NEISD Holiday
    scan_interval: 7200
    value_template: >
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set neisd_holiday =  value_json.SCHOOL.neisd_holidays[ today ] %}
      {{neisd_holiday}}

  - platform: rest
    resource: https://raw.githubusercontent.com/atomicpapa/hassconfig/master/json_data/school_holidays.json
    name: SST Holiday
    scan_interval: 7200
    value_template: >
      {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
      {% set sst_holiday =  value_json.SCHOOL.sst_holidays[ today ] %}
      {{sst_holiday}}

automation:
  - alias: School Holiday
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.neisd_holiday
          - sensor.sst_holiday

    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ states('trigger.entity_id') != 'unknown' }}"
        - condition: template
          value_template: "{{ states.trigger.entity_id.state | trim != '' }}"

    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.school_mode

  - alias: 'School - Weekends'
    initial_state: 'on'
    trigger:
      platform: time
      at: '00:15:00'

    condition:
      condition: time
      weekday:
        - sat
        - sun

    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.school_mode

  # - alias: School Day Alarm
  #   initial_state: 'on'
  #   trigger:
  #     platform: time
  #     at: '06:00:00'
  #
  #   condition:
  #     condition: state
  #     entity_id: input_boolean.school_mode
  #     state: 'on'
  #
  #   action:
  #     - service: script.speech_engine
  #       data:
  #         call_school_day_alarm: 1
  #         call_outside_weather: 1
  #         call_weather_today: 1


  - alias: 'School Day Morning Startup'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:10:00'

    condition:
      - condition: state
        entity_id: input_boolean.school_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

    action:
      - service: light.turn_on
        entity_id:
          - light.girls
          - light.boy
          - light.living_room_dimmer
          - light.desk_lamp
          - light.hall
          - light.entry_hall

      - service: script.speech_engine
        data:
          call_school_day_alarm: 1
          call_inside_weather: 1
          call_outside_weather: 1
          call_pollen_today: 1
          call_garbage_collection: 1
          call_holiday: 1

      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "Today is a School day.  I will turn on some lights to get this day started! (https://www.amazon.com/dp/B07P8WZN84/)",
            "Up at the crack of Dawn for School.  We need some lights on. (https://www.amazon.com/dp/B07P8WZN84/)",
            "This is way early.  We need some lights on. (https://www.amazon.com/dp/B07P8WZN84/)",
            "Time to wake up the house with some gentle lighting. (https://www.amazon.com/dp/B07P8WZN84/)"
            ] | random + " #Hue"}}

  - alias: 'Med Check'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:30:00'

    condition:
      - condition: state
        entity_id: input_boolen.school_mode
        state: 'on'

    action:
      - service: script.speech_engine
        data:
          call_no_announcement: 1
          call_med_reminder: 1

      # - service: script.notify_engine
      #   data_template:
      #     who: 'glenn'
      #     value1: "Someone hasn't had their meds yet!"
      #     title: "Med Check!!"

  - alias: 'School Day Morning Wind Down'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '07:30:00'

    condition:
      - condition: state
        entity_id: input_boolean.school_mode
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

    action:
      - service: light.turn_off
        entity_id:
          - light.girls
          - light.boy
          - light.hall
          - light.entry_hall
