---

# Config for Twitter notify component. Some Automations
# will post an update to Twitter when triggered.

# See also: /Automations folder

notify:
  - name: twitter
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_secret

# sensor:
#   - name: twitter
#     platform: twitter
#     consumer_key: !secret twitter_consumer_key
#     consumer_secret: !secret twitter_consumer_secret
#     access_token: !secret twitter_access_token
#     access_token_secret: !secret twitter_access_secret
#     screen_names:
#       - Atomic_HA

automation:

  # Send data from IFTTT to MQTT stream so it can be picked up as sensors
  - alias: Twitter Followers
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: new_follower

    action:
      - service_template: mqtt.publish
        data:
          topic: /hass/twitter/new_follower
          payload_template: '{{ trigger.event.data }}'
          retain: true

  # Play a chirp over GH's when we get a new follower
  - alias: Twitter Followers Chirp
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          action: new_follower

    condition:
      - condition: time
        after: "09:00:00"
        before: "22:00:00"

    action:
      - service: media_player.media_play
        data_template:
          entity_id: "all"
          media_content_id: "https://raw.githubusercontent.com/atomicpapa/hassconfig/master/www/sounds/twitter-chirp.mp3"
          media_content_type: audio/mp4
