---

############################################################
#                                                          #
# Core Component Config for Weather                        #
# https://www.home-assistant.io/components/openweathermap/ #
# https://www.home-assistant.io/components/darksky/        #
#                                                          #
############################################################

weather:
  - platform: openweathermap
    api_key: !secret owm_key

  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
    
sensor:
  - platform: openweathermap
    api_key: !secret owm_key
    monitored_conditions:
      - weather
      - temperature
      - humidity

  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - precip_probability
      - uv_index
      - minutely_summary
      # - apparent_temperature_high
      - alerts

  - platform: template
    sensors:
      heat_index:
        friendly_name: 'Heat Incex'
        #formula taken from http://www.srh.noaa.gov/ama/?n=heatindex
        value_template: '{{ (((-42.379 + (2.04901523*((states.weather.dark_sky.attributes.temperature|float))) + (10.14333127*(states.weather.dark_sky.attributes.humidity|float)) - (0.22475541*((states.weather.dark_sky.attributes.temperature|float))*(states.weather.dark_sky.attributes.humidity|float)) - (6.83783 * (10**(-3))*(((states.weather.dark_sky.attributes.temperature|float))**2)) - (5.481717 * (10**(-2))*((states.weather.dark_sky.attributes.humidity|float)**2)) + (1.22874 * (10**(-3))*(((states.weather.dark_sky.attributes.temperature|float))**2*(states.weather.dark_sky.attributes.humidity|float))) + (8.5282 * (10**(-4))*(((states.weather.dark_sky.attributes.temperature|float))*(states.weather.dark_sky.attributes.humidity|float)**2)) - (1.99 * (10**(-6))*(((states.weather.dark_sky.attributes.temperature|float))**2)*(states.weather.dark_sky.attributes.humidity|float)**2))))|round(1) }}'
        unit_of_measurement: '°F'


# Config for IQVIA allergen, cold, & disease sensors.
# https://www.home-assistant.io/components/iqvia/
# see also: /automations/weather.yaml
iqvia:
  zip_code: "78209" #!secret zip_code
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_index_today
    - allergy_index_tomorrow
    - asthma_average_forecasted
    - asthma_index_today
    - asthma_index_tomorrow
    - disease_average_forecasted
    - disease_index_today

camera:
  - platform: generic
    still_image_url: 'https://icons.wxug.com/data/weather-maps/radar/united-states/san-antonio-texas-region-current-radar-animation.gif'
    name: 'Local Radar'
  - platform: generic
    still_image_url: 'https://radar.weather.gov/Conus/full_loop.php'
    name: 'National Radar'

# Automations related to severe weather conditions

automation:

# NOAA Alerts
  - alias: Noaa Alert - Text
    initial_state: 'on'
    trigger:
      entity_id: sensor.dark_sky_alerts
      from: ‘0’
      platform: state
    action:
      - service: persistent_notification.create
        data_template:
          message: ‘{{ states.sensor.dark_sky_alerts.attributes.description }}’

      - service: notify.pushbullet
        data_template:
          message: '{{ states.sensor.noaa_alerts_txz205.attributes.headline }}'
        
  - alias: Noaa Alert - TTS
    initial_state: 'on'
    trigger:
      entity_id: sensor.dark_sky_alerts
      from: ‘0’
      platform: state
  
    action:
      - service: script.speech_engine
        data:
          call_no_announcement: 1
          call_weather_alert: 1
# Allergy Notifications