---

# 6am automations

- alias: Set AC to 76
  initial_state: 'on'
  trigger:
     platform: time
     at: '06:00:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat
        hvac_mode: cool
        temperature: 76
