---
########  10pm Automations  #########

- alias: Set AC to 73
  initial_state: 'on'
  trigger:
    platform: time
    at: '22:00:00'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat
        hvac_mode: cool
        temperature: 73

- alias: 'Girls Allergy Meds'
  initial_state: 'on'
  trigger:
    platform: time
    at: '22:01:00'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: person.lola
        state: "home"
      - condition: state
        entity_id: person.emmy
        state: 'home'

  action:
    - service: script.speech_engine
      data:
        call_no_announcement: 1
        call_girls_allergy_meds: 1
